name: Lab 3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t lab3 .

      - name: Save Docker image
        run: |
          docker save lab3 -o lab3.tar
          mv lab3.tar $GITHUB_WORKSPACE/lab3.tar
          echo "::set-output name=DevOps/lab3/::$GITHUB_WORKSPACE/lab3.tar"
        id: save

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: ${{ steps.save.outputs.image_path }}