name: Lab 3

on:
  push:
    paths:
      - 'DevOps/lab3/files/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Install project dependencies
        run: |
          pip install -r DevOps/lab3/requirements.txt
      - name: Run script
        run: |
          python DevOps/lab3/main.py