name: Docker Build and Main Script

on:
  push:
    paths:
      - 'DevOps/lab3/files/**'

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t lab3 ./DevOps/lab3

      - name: Run main.py script in Docker container
        run: |
          docker run -v $(pwd)/DevOps/lab3/reports:/app/DevOps/lab3/reports lab3 python DevOps/lab3/main.py

      - name: Upload main.py result artifact
        uses: actions/upload-artifact@v2
        with:
          name: main-result
          path: DevOps/lab3/reports