name: Docker Build and Main Script

on:
  push:
    paths:
      - 'DevOps/lab3/files/**'

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t lab3 ./DevOps/lab3

      - name: Run main.py script in Docker container
        run: docker run -v $(pwd)/reports:/app/reports lab3 python /app/main.py

      - name: Commit and push changes
        run: |
            cd /app/reports
          
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            
            git add *
            git commit -m "Add new report" || true
            git push