name: Docker Build and Main Script

on:
  push:
    paths:
      - 'DevOps/lab3/files/**'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t lab3 ./DevOps/lab3

      - name: Run docker container
        run: docker run --name lab3_container lab3

      - name: Copy generated file
        run: docker cp lab3_container:/app/reports/output.json $GITHUB_WORKSPACE/DevOps/lab3/reports

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add output.json
          git commit -m "Add output.json"
          git push
